"""fixed profile rel

Revision ID: 374feb609c7a
Revises: ac10d6a07918
Create Date: 2024-03-11 23:13:12.146019

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "374feb609c7a"
down_revision: Union[str, None] = "ac10d6a07918"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles",
        sa.Column(
            "user_telegram_id",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "phone",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "email", sa.String(), nullable=True
        ),
        sa.Column(
            "new_cafes_notify",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_telegram_id"],
            ["users.telegram_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_telegram_id"),
    )
    op.create_index(
        op.f("ix_profiles_email"),
        "profiles",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_profiles_phone"),
        "profiles",
        ["phone"],
        unique=True,
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.drop_index(
        "ix_users_email", table_name="users"
    )
    op.drop_index(
        "ix_users_phone", table_name="users"
    )
    op.drop_column("users", "phone")
    op.drop_column("users", "email")
    op.drop_column("users", "notify")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "notify",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "email",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "phone",
            sa.BIGINT(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_users_phone",
        "users",
        ["phone"],
        unique=True,
    )
    op.create_index(
        "ix_users_email",
        "users",
        ["email"],
        unique=True,
    )
    op.alter_column(
        "users",
        "telegram_id",
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.drop_index(
        op.f("ix_profiles_phone"),
        table_name="profiles",
    )
    op.drop_index(
        op.f("ix_profiles_email"),
        table_name="profiles",
    )
    op.drop_table("profiles")
    # ### end Alembic commands ###
