"""added requests counter

Revision ID: 5c4ba5485f76
Revises: d73d24d088ba
Create Date: 2024-03-11 23:41:13.228575

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5c4ba5485f76"
down_revision: Union[str, None] = "d73d24d088ba"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "general_requests",
            sa.Integer(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("profiles", "general_requests")
    # ### end Alembic commands ###
