"""fixed user requests columns

Revision ID: 5d6082a49b28
Revises: c18a88dc28db
Create Date: 2024-03-12 01:55:17.556092

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5d6082a49b28"
down_revision: Union[str, None] = "c18a88dc28db"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "request_type",
            sa.String(),
            nullable=False,
        ),
    )
    op.drop_column("requests", "type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "requests",
        sa.Column(
            "type",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("requests", "request_type")
    # ### end Alembic commands ###
