"""fixed requests author_telegram_id column

Revision ID: 69b9b351d865
Revises: 5d6082a49b28
Create Date: 2024-03-12 02:19:10.736097

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "69b9b351d865"
down_revision: Union[str, None] = "5d6082a49b28"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "requests_author_telegram_id_key",
        "requests",
        type_="unique",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "requests_author_telegram_id_key",
        "requests",
        ["author_telegram_id"],
    )
    # ### end Alembic commands ###
