"""added phone confirmed

Revision ID: 8edfb97ab027
Revises: 5c4ba5485f76
Create Date: 2024-03-11 23:54:03.670207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8edfb97ab027"
down_revision: Union[str, None] = "5c4ba5485f76"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "is_phone_confirmed",
            sa.Integer(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(
        "profiles", "is_phone_confirmed"
    )
    # ### end Alembic commands ###
