"""fixed user requests rel

Revision ID: c18a88dc28db
Revises: 5db77e9e6423
Create Date: 2024-03-12 01:15:27.307614

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c18a88dc28db"
down_revision: Union[str, None] = "5db77e9e6423"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "requests_author_telegram_id_fkey",
        "requests",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "requests",
        "profiles",
        ["author_telegram_id"],
        ["user_telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "requests", type_="foreignkey"
    )
    op.create_foreign_key(
        "requests_author_telegram_id_fkey",
        "requests",
        "users",
        ["author_telegram_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
