"""initial

Revision ID: d4a1479c4474
Revises: 
Create Date: 2024-03-10 19:02:34.544378

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4a1479c4474"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column(
            "telegram_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "is_bot", sa.Boolean(), nullable=True
        ),
        sa.Column(
            "first_name",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "last_name",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "username", sa.String(), nullable=True
        ),
        sa.Column(
            "language_code",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "is_premium",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "phone",
            sa.BigInteger(),
            nullable=True,
        ),
        sa.Column(
            "email", sa.String(), nullable=True
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )
    op.create_index(
        op.f("ix_users_phone"),
        "users",
        ["phone"],
        unique=True,
    )
    op.create_index(
        op.f("ix_users_telegram_id"),
        "users",
        ["telegram_id"],
        unique=True,
    )
    op.create_table(
        "updates",
        sa.Column(
            "user_id", sa.String(), nullable=False
        ),
        sa.Column(
            "update_id",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "update_type",
            sa.String(),
            nullable=False,
        ),
        sa.Column(
            "update_data",
            postgresql.JSONB(
                astext_type=sa.Text()
            ),
            nullable=True,
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("updates")
    op.drop_index(
        op.f("ix_users_telegram_id"),
        table_name="users",
    )
    op.drop_index(
        op.f("ix_users_phone"), table_name="users"
    )
    op.drop_index(
        op.f("ix_users_email"), table_name="users"
    )
    op.drop_table("users")
    # ### end Alembic commands ###
