"""renamed general_requests to general_search_requests

Revision ID: d4b3c7c9526e
Revises: 8edfb97ab027
Create Date: 2024-03-12 00:35:20.981851

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d4b3c7c9526e"
down_revision: Union[str, None] = "8edfb97ab027"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "general_search_requests",
            sa.Integer(),
            nullable=True,
        ),
    )
    op.drop_column("profiles", "general_requests")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "general_requests",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column(
        "profiles", "general_search_requests"
    )
    # ### end Alembic commands ###
