"""added inline requests counter

Revision ID: 1ce046c47f92
Revises: 58fb855701cf
Create Date: 2024-03-12 19:17:39.743281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1ce046c47f92"
down_revision: Union[str, None] = "58fb855701cf"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "inline_search_requests",
        existing_type=sa.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "inline_search_requests",
        existing_type=sa.BIGINT(),
        nullable=True,
    )
    # ### end Alembic commands ###
