"""adding is_admin

Revision ID: 2145e507643a
Revises: 5bbd6af4abe1
Create Date: 2024-05-20 01:42:20.872501

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2145e507643a"
down_revision: Union[str, None] = "5bbd6af4abe1"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "is_admin",
            sa.Boolean(),
            nullable=True,
        ),
    )
    op.alter_column(
        "profiles",
        "is_phone_confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "profiles",
        "is_phone_confirmed",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.drop_column("profiles", "is_admin")
    # ### end Alembic commands ###
