"""added user preferences

Revision ID: 60cea855ad06
Revises: 2145e507643a
Create Date: 2024-05-20 13:27:39.297363

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "60cea855ad06"
down_revision: Union[str, None] = "2145e507643a"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column(
            "profile_id",
            sa.BigInteger(),
            nullable=False,
        ),
        sa.Column(
            "new_cafes_notify",
            sa.Boolean(),
            nullable=True,
        ),
        sa.Column(
            "max_search_distance",
            sa.Integer(),
            nullable=True,
        ),
        sa.Column(
            "id", sa.String(), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.user_telegram_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("profiles", "new_cafes_notify")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "new_cafes_notify",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_table("preferences")
    # ### end Alembic commands ###
