"""fixing user preferences

Revision ID: f863a24f25c7
Revises: 184b39bf4a00
Create Date: 2024-05-20 14:07:19.378343

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f863a24f25c7"
down_revision: Union[str, None] = "184b39bf4a00"
branch_labels: Union[str, Sequence[str], None] = (
    None
)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profiles",
        sa.Column(
            "preferences_id",
            sa.String(),
            nullable=True,
        ),
    )
    op.create_unique_constraint(
        None, "profiles", ["preferences_id"]
    )
    op.create_foreign_key(
        None,
        "profiles",
        "preferences",
        ["preferences_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        None, "profiles", type_="foreignkey"
    )
    op.drop_constraint(
        None, "profiles", type_="unique"
    )
    op.drop_column("profiles", "preferences_id")
    # ### end Alembic commands ###
