# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/image_service.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import (
    descriptor as _descriptor,
)
from google.protobuf import (
    descriptor_pool as _descriptor_pool,
)
from google.protobuf import (
    symbol_database as _symbol_database,
)
from google.protobuf.internal import (
    builder as _builder,
)

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x19proto/image_service.proto\x12\x05image"#\n\x10PostImageRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c"!\n\x11PostImageResponse\x12\x0c\n\x04uuid\x18\x01 \x01(\t"\x1f\n\x0fGetImageRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t"#\n\x10GetImageResponse\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x32\x8b\x01\n\x0cImageService\x12>\n\tPostImage\x12\x17.image.PostImageRequest\x1a\x18.image.PostImageResponse\x12;\n\x08GetImage\x12\x16.image.GetImageRequest\x1a\x17.image.GetImageResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(
    DESCRIPTOR, _globals
)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR,
    "proto.image_service_pb2",
    _globals,
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals[
        "_POSTIMAGEREQUEST"
    ]._serialized_start = 36
    _globals[
        "_POSTIMAGEREQUEST"
    ]._serialized_end = 71
    _globals[
        "_POSTIMAGERESPONSE"
    ]._serialized_start = 73
    _globals[
        "_POSTIMAGERESPONSE"
    ]._serialized_end = 106
    _globals[
        "_GETIMAGEREQUEST"
    ]._serialized_start = 108
    _globals[
        "_GETIMAGEREQUEST"
    ]._serialized_end = 139
    _globals[
        "_GETIMAGERESPONSE"
    ]._serialized_start = 141
    _globals[
        "_GETIMAGERESPONSE"
    ]._serialized_end = 176
    _globals[
        "_IMAGESERVICE"
    ]._serialized_start = 179
    _globals["_IMAGESERVICE"]._serialized_end = (
        318
    )
# @@protoc_insertion_point(module_scope)
